Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "ubuntu14"
  c.vm.box_url = "file:///C:/DevOps/Vagrant_Box/precise64.box"
  c.vm.hostname = "default-ubuntu14"
  c.ssh.insert_key = "false"
  c.ssh.private_key_path = "C:/DevOps/TDD/vagrant/keys/vagrant"
  c.vm.network(:private_network, {:ip=>"192.168.33.38"})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
  end
end
